# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import expensetraq.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('C', 'Created'), ('A', 'Approved'), ('D', 'Denied')], default='C', max_length=2)),
                ('paid_by', models.CharField(choices=[('COMPANY', 'Employee Paid'), ('EMPLOYEE', 'Company Paid')], max_length=2)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to=expensetraq.core.models.receipt_directory_path)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gl_code', models.CharField(max_length=30, verbose_name='GL Code')),
                ('receipt_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day_of_month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExpenseType')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recur_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expenselimit',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExpenseType'),
        ),
        migrations.AddField(
            model_name='expenselimit',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExpenseType'),
        ),
        migrations.AddField(
            model_name='expense',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
