# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-salesman', '-transaction_date', '-created')},
        ),
        migrations.AddField(
            model_name='salesman',
            name='daily_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
