# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.CharField(choices=[('E', 'Employee Paid'), ('C', 'Company Paid')], max_length=2),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
