# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170508_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetypecode',
            options={},
        ),
        migrations.RemoveField(
            model_name='expensetypecode',
            name='created',
        ),
        migrations.RemoveField(
            model_name='expensetypecode',
            name='modified',
        ),
    ]
