# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170829_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanCompanyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('gp_vendor_code', models.CharField(max_length=100)),
                ('company_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExpenseType')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='salesman',
            old_name='gp_vendor_code',
            new_name='gp_cash_vendor_code',
        ),
        migrations.RemoveField(
            model_name='companycard',
            name='gp_vendor_code',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='company_cards',
        ),
        migrations.AddField(
            model_name='salesmancompanycard',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cards', to='core.Salesman'),
        ),
    ]
