# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170919_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gl_code_suffix', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensetypecode',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='expensetype',
            name='gl_code_prefix',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpenseTypeCode',
        ),
        migrations.AddField(
            model_name='salesmanexpensetype',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ExpenseType'),
        ),
        migrations.AddField(
            model_name='salesmanexpensetype',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='core.Salesman'),
        ),
    ]
