# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170509_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pushed_to_gp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesman',
            name='has_company_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.CharField(choices=[('E', 'Employee Paid'), ('C', 'Company Paid')], default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='expensetypecode',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_codes', to='core.ExpenseType'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='day_of_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)]),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='user',
            field=models.OneToOneField(error_messages={'unique': 'Salesman already on-boarded.'}, on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
