# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170919_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseline',
            name='region',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='regions',
        ),
    ]
