# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170921_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselimit',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SalesmanExpenseType'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SalesmanExpenseType'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SalesmanExpenseType'),
        ),
    ]
