# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170921_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
