# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171003_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanexpensetype',
            name='name',
        ),
    ]
